[[HYPRE]]
arch = "aarch64"
git-tree-sha1 = "bc233c99709eaf5536957b8a42ef89a7f4ddaa00"
os = "macos"

    [[HYPRE.download]]
    sha256 = "e16f1a74032932da521a62be76105a41d0344d6f4b15c3e6fbf5d84f5179829b"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.aarch64-apple-darwin.tar.gz"
[[HYPRE]]
arch = "aarch64"
git-tree-sha1 = "4c33cd6e1463051b5af592d1aa8d4d27ee103b1f"
libc = "glibc"
os = "linux"

    [[HYPRE.download]]
    sha256 = "6a739deec03f8976f0107f78891175894ed1c434f7f5894a24b28214b414ddb7"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.aarch64-linux-gnu.tar.gz"
[[HYPRE]]
arch = "aarch64"
git-tree-sha1 = "afe7f28585b4bbe257e903e28f653286ca9da404"
libc = "musl"
os = "linux"

    [[HYPRE.download]]
    sha256 = "54ff3b987f6ac981abe12df0d1021fc063a92c80ef96fcd28e4bfa867fb3f218"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.aarch64-linux-musl.tar.gz"
[[HYPRE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c66076619217582aa3d4d5a1ec1dcd5565a8d91a"
libc = "glibc"
os = "linux"

    [[HYPRE.download]]
    sha256 = "4d52e609a2f1d84f5d966e2e8d845baec99f9e2d43972beb6f9935c7f32fd691"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.armv6l-linux-gnueabihf.tar.gz"
[[HYPRE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "154d4d4e5745a787e4425f707b1c8aff92905fa9"
libc = "musl"
os = "linux"

    [[HYPRE.download]]
    sha256 = "024b86f5c834a0e235f73881fd600687607d788bab7b6d3b26f5da65cc284d1b"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.armv6l-linux-musleabihf.tar.gz"
[[HYPRE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "131864070134bd29a742e187f1465c503ad20953"
libc = "glibc"
os = "linux"

    [[HYPRE.download]]
    sha256 = "22014263de38a2224482bd9baad876764ce1aba9d931e1f6d09bd95f8cbb710a"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.armv7l-linux-gnueabihf.tar.gz"
[[HYPRE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ec98b07aacaf5b8ccaba9e04ffab97749753b84d"
libc = "musl"
os = "linux"

    [[HYPRE.download]]
    sha256 = "bb40af1bbc1b2be1cb1e20c100f008cf731fc943914d8413c1b905edd4c1ca48"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.armv7l-linux-musleabihf.tar.gz"
[[HYPRE]]
arch = "i686"
git-tree-sha1 = "c0e924e4ae2c0808b56e2fb998a75995651eccd6"
libc = "glibc"
os = "linux"

    [[HYPRE.download]]
    sha256 = "d2994106d3e6eed0d8cafd2d8c8aff5af3a3137203078e426cad91e6043822a8"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.i686-linux-gnu.tar.gz"
[[HYPRE]]
arch = "i686"
git-tree-sha1 = "6fc7f69bdf3ec8b6444a4c1ef90b929ba5e9b77d"
libc = "musl"
os = "linux"

    [[HYPRE.download]]
    sha256 = "1da058f35c0f15c5a31fe3ce046bfa257c00f154e41e6e1eb12a0aa96bc65aa6"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.i686-linux-musl.tar.gz"
[[HYPRE]]
arch = "i686"
git-tree-sha1 = "12bc2f5b5a26832de07c8be8f02c8da24516349e"
os = "windows"

    [[HYPRE.download]]
    sha256 = "9b336478c3477f925025fea9858acf29cbd5eb6abf65028af240480b83fcff66"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.i686-w64-mingw32.tar.gz"
[[HYPRE]]
arch = "powerpc64le"
git-tree-sha1 = "1429c8453b2bf3a4240efce619d2f2c48ee1ae69"
libc = "glibc"
os = "linux"

    [[HYPRE.download]]
    sha256 = "7c02f0254bed1540377fb2520882da7004133308cdf555bbf2d26d42f87f7fc9"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.powerpc64le-linux-gnu.tar.gz"
[[HYPRE]]
arch = "x86_64"
git-tree-sha1 = "b0b54bf4f01a08cbbe037e29e882dda1fa0a0dc1"
os = "macos"

    [[HYPRE.download]]
    sha256 = "4271c9875ea858d1f3d679ef3b7fc101a41bb148131a990bd9da10d36bb5d288"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.x86_64-apple-darwin.tar.gz"
[[HYPRE]]
arch = "x86_64"
git-tree-sha1 = "deca5e3d470ebecc82b57d40edb0a25053adfe93"
libc = "glibc"
os = "linux"

    [[HYPRE.download]]
    sha256 = "8ce2b02fa06f73b8df726ba3dab530560c5fdd9aa5cdaf017a78fbd4a87f1de4"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.x86_64-linux-gnu.tar.gz"
[[HYPRE]]
arch = "x86_64"
git-tree-sha1 = "e2a9026889d9ef9eacf3549f00d1d2e02e6b386d"
libc = "musl"
os = "linux"

    [[HYPRE.download]]
    sha256 = "1d905fc89f9a1b92518e54a1eb52ce5c61225722b5af6dd043d8a35a5451d884"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.x86_64-linux-musl.tar.gz"
[[HYPRE]]
arch = "x86_64"
git-tree-sha1 = "a3f08eb7d861164505020b4a1a2d81b84d2997ad"
os = "freebsd"

    [[HYPRE.download]]
    sha256 = "3824767a2daf6340fc501018643685b3f3cccc81fbc5ef336e13e0cef4846ada"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.x86_64-unknown-freebsd.tar.gz"
[[HYPRE]]
arch = "x86_64"
git-tree-sha1 = "4b4daef02196c3edcf48a71e13683f0f23669786"
os = "windows"

    [[HYPRE.download]]
    sha256 = "d81124ae7d50785a922d7fc98f5e66af34718efafd440033fb92acf3bd3a2cc6"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.0+0/HYPRE.v2.23.0.x86_64-w64-mingw32.tar.gz"
