[[HYPRE]]
arch = "aarch64"
git-tree-sha1 = "a75318372b028b10e699bdf84554990900f70ed4"
lazy = true
mpi = "mpich"
os = "macos"

    [[HYPRE.download]]
    sha256 = "e20daea95915fd499f6d1abfc338f34cc2ffb69aa2629589dcb6cde6ef9a3b54"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "aarch64"
git-tree-sha1 = "381fb8465915000c7fd8ebdc787444d77f555389"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[HYPRE.download]]
    sha256 = "fce311b3af9a299b879bf55d16c1c187dcc9c2e7f6d788f7aab3884deb727e76"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[HYPRE]]
arch = "aarch64"
git-tree-sha1 = "b8a9eb2eaa15fe46296591254b48e3f82229cae8"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[HYPRE.download]]
    sha256 = "3719915305bc6896dca22419e0258b5ef121bf4586ddfce3d850ff2c252b7d5c"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "aarch64"
git-tree-sha1 = "0e63ee2524e96371666e03335755f111e5e5a28a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[HYPRE.download]]
    sha256 = "bafb5957c91fe644e310bac7bfb14f8ecd37c8157661fd878c536dd4c099d594"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[HYPRE]]
arch = "aarch64"
git-tree-sha1 = "43a5bf3951c5154cebf12da7ec02705e9fc171dd"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[HYPRE.download]]
    sha256 = "522480e8afff87e20e5c57990679863b0827b69960bf41cbfc19cd57d71545be"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.aarch64-linux-musl-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "74500e517b78785602bb95a4898cbd25d337635f"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[HYPRE.download]]
    sha256 = "d3e5e814ad1bfba8f43d90190c671d2a5bb594dfbbe31f418eb81d7581090458"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.armv6l-linux-gnueabihf-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a0d62a604773b79fba2f7e7341cd80f173eb2f6e"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[HYPRE.download]]
    sha256 = "2e70756c60fdc8b79ca1d3f42d6f8e8eea58e8bb56b691a41d1f2fadacb08a9c"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.armv6l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[HYPRE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c93404aedaac5be62a57ab5cc693f9f884ea68dd"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[HYPRE.download]]
    sha256 = "c04cbf15b8322e256c79680e5c01b04949a2c52f71e11403dbdf33da973001e1"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.armv6l-linux-musleabihf-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fad76ee371078e3817028c7a79f6db80aa71de81"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[HYPRE.download]]
    sha256 = "44682e0c5f11328cd3edf5c86a1f4f8a75856adb76f6bf4f8be7124d98df5b0a"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.armv7l-linux-gnueabihf-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6433962b8ad2ff1cb55f41f3eed6937add8b6176"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[HYPRE.download]]
    sha256 = "d7b641f2c3027fdfeebf9deb6550366895628aa19f5bd6a998a761e0e9dd1050"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.armv7l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[HYPRE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1a0ee53f58f56bed4e699f756ef74ca2832ad0d8"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[HYPRE.download]]
    sha256 = "cf5eabe50abb20b477da14277eac05a04667176a44a40cce5d371d3b63fbbded"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.armv7l-linux-musleabihf-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "i686"
git-tree-sha1 = "a34429526a20f51ad1e7eeee8101ed44b8eb467e"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[HYPRE.download]]
    sha256 = "c1beb0ff47f28cdf5b11d4000bfbcfd2c3bbe48692ddf497285d24d75c8313d4"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.i686-linux-gnu-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "i686"
git-tree-sha1 = "3932016dedc41880e907f932c82fbd9bad74c0af"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[HYPRE.download]]
    sha256 = "acc9daf14fc85f14116fd66cfab36c7e672d2d1b14280c14081de469ae55d28d"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.i686-linux-gnu-mpi+mpitrampoline.tar.gz"
[[HYPRE]]
arch = "i686"
git-tree-sha1 = "2119796072bd756db8a1ddb73f77c8fd449ea7de"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[HYPRE.download]]
    sha256 = "c708a4c67b6317e2d782fc0c477594a1cb3f90a7eb2753967d4158afb8bcf6fe"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.i686-linux-musl-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "i686"
git-tree-sha1 = "ca8fef8105e274596600bb19a5ef3e22385311a2"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[HYPRE.download]]
    sha256 = "21c8fdc65b0b7cdde4e20583482eadc08524d7b75e8d29b33222a7eb95d530ee"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.i686-w64-mingw32-mpi+microsoftmpi.tar.gz"
[[HYPRE]]
arch = "powerpc64le"
git-tree-sha1 = "b59444dd901bd3648c0808b1b9ff9bd3af9d555d"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[HYPRE.download]]
    sha256 = "9ccc086ac059a8a1d3bb25d73e627b66d1d04d240ff26028592ecca1adff1005"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "powerpc64le"
git-tree-sha1 = "dc5af87a392a3f5b1be802bd866baa6d5403bdb2"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[HYPRE.download]]
    sha256 = "1cec15c76c236cbcbde380ff06f3e1508d54331e17b4ed2b0246b851636c220e"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[HYPRE]]
arch = "x86_64"
git-tree-sha1 = "c91fec1b4a805e36954f203013274e687f16b32a"
lazy = true
mpi = "mpich"
os = "macos"

    [[HYPRE.download]]
    sha256 = "c3d0daf808eaf255ffe9b702e4697015698f382b80b9f4b13a2f819a0bc8f76c"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "x86_64"
git-tree-sha1 = "ba8c26d3e262e5b02a6915ec4e6f4d5c4980b130"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[HYPRE.download]]
    sha256 = "6d09ccae0a11012706e35dd0780e88ce3f538c4ce6175ac74433bdfcfa6789eb"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[HYPRE]]
arch = "x86_64"
git-tree-sha1 = "799504d1e24aff1d29cf943fd3f52b2073f82d30"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[HYPRE.download]]
    sha256 = "9c39bcc6195f5bacdd92125d79622129b4d445244c268041fdf58ffc1b5e06a9"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "x86_64"
git-tree-sha1 = "deec92fddf9c5891ec4c5e9734fbfabfc58abc35"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[HYPRE.download]]
    sha256 = "a4579fb96f41736cc5ad68fef5db56262f96289cf3cea0565155db4285102a6c"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[HYPRE]]
arch = "x86_64"
git-tree-sha1 = "4b611e483c3c273cb60565fb1128b49758094177"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[HYPRE.download]]
    sha256 = "b94b3bb97750d525fd5625f9ca35af376a3ae7574496797f4d09ba5585c260fa"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.x86_64-linux-musl-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "x86_64"
git-tree-sha1 = "c5b793e225fef96a835efa7f00c6c233b3087c40"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[HYPRE.download]]
    sha256 = "0e1734143548ae3e9945341e378141a169f29c115a0253386105c0221178f8c4"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[HYPRE]]
arch = "x86_64"
git-tree-sha1 = "bd24003caa91fd93c08910a746d0f70cfbc8bc68"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[HYPRE.download]]
    sha256 = "8f16ca7cdac45f5a8967492bd3017fc1dc62038e644111bdfcb3cf8b201b3118"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE_jll.jl/releases/download/HYPRE-v2.23.1+0/HYPRE.v2.23.1.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
