# Autogenerated wrapper script for HYPRE_jll for aarch64-apple-darwin-mpi+mpiabi
export libHYPRE

using libblastrampoline_jll
using LLVMOpenMP_jll
using MPIABI_jll
JLLWrappers.@generate_wrapper_header("HYPRE")
JLLWrappers.@declare_library_product(libHYPRE, "@rpath/libHYPRE.301.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, LLVMOpenMP_jll, MPIABI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libHYPRE,
        "lib/libHYPRE.3.1.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
